<?php

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function dan_payne_news_theme_suggestions_views_view_row_rss_alter(array &$suggestions, array $variables) {
  $suggestions[] = "views_view_row_rss__" . $variables['view']->id();
}

/**
 * Implements hook_preprocess_views_view_row_rss().
 */
function dan_payne_news_preprocess_views_view_row_rss(&$variables) {
  if ($variables['view']->id() === 'taxonomy_term') {

    global $base_url;

    // @fixme Find a better way to get the right image media url.
    if (!empty($variables['row']->description['#node']->field_news_media)) {
      $image = render($variables['row']->description['#node']->field_news_media->view('rss'));
      $doc = new DOMDocument();
      @$doc->loadHTML($image);
      $tags = $doc->getElementsByTagName('img');
      foreach ($tags as $tag) {
        $imageSrc = $tag->getAttribute('src');
      }
      if (!empty($imageSrc)) {
        $variables['image_src'] = $base_url . $imageSrc;
      }
    }

    // Override the description with a plain text string.
    if (!empty($variables['row']->description['#node']->body)) {
      $summary = render($variables['row']->description['#node']->body->view('teaser'));
      $variables['description'] = strip_tags($summary);
    }
  }
}