<?php

/**
 * Implements hook_preprocess_field().
 */
function danpayne_theme_preprocess_field(&$variables, $hook) {

  $element = $variables['element'];

  if ($element['#field_name'] == 'field_social_network_follow_link') {
    foreach($variables['items'] as $key => $item) {
      $class_name = strtolower($item['content']['#title']);
      $variables['items'][$key]['content']['#options']['attributes']['class'][] = 'sprite-social-media';
      $variables['items'][$key]['content']['#options']['attributes']['class'][] = 'sprite-social-media-' . $class_name;
      $variables['items'][$key]['content']['#options']['attributes']['target'] = '_blank';
    }
  }
}
